### ISSUE TITLE
activation from rule page doesn't take effect

### ISSUE THREAD

**Issue by origal** [requestly/requestly-browser-extension#141]
hey,

when i enter a 'redirect request rule' existing page and switch 'Inactive' to 'Active' and than go back to the main rules page by clicking the 'Requestly' logo on the upper right corner, the rule I activated is still shown as Inactive.

I'm using chrome Version 53.0.2785.143 (64-bit) on a Mac running macOs Sierra.

Thanks and sorry if this is a known issue.

**Comment by sachinjain024** [comment]
@origal Thanks for asking this question.
Actually after changing the status of rule on editor screen, you need to click on "Save Button". If you do not press save button and go back, your changes are not persisted. Hence you see no effect on List screen.

Let me know if it answers your question.

**Comment by origal** [comment]
@sachinjain024 Thanks for the quick reply. Understood.

As a side note, I must say that in my humble opinion this flow is very unclear, as in the list screen you just flip the same switch in order to activate or deactivate rules.

I would expect the save button to be required only after editing a rule, and the activate switch to work regardless of saving the rule in this screen, but again that's of course just my opinion.

Thanks again for your answer.

**Comment by a7madgamal** [comment]
I agree with @origal 
I also thought it was a bug :D

**Comment by sachinjain024** [comment]
Thanks @origal @a7madgamal for your suggestions. There is an issue with suggested user experience.

Suppose I implement Save functionality on Toggling Rule Status. Now Consider this scenario:
1. User starts to create the rule so all fields are empty
2. By default a rule is inactive So user may want to turn on the rule while creation
3. In this case save will be triggered and user will see errors related to incomplete fields.

This is why this workflow is not implemented. Once again, thanks for your suggestions.
In the next case, what we can do is to identify if user has made certain changes and still try to click on back/close button then we can show him confirmation dialog.

**Comment by origal** [comment]
@sachinjain024 ..or maybe show the activate button only when a user edits an existing rule and not creating a new one.. or have some validation for the inputs before allowing to activate..
